/*******************************************************************************
 * Copyright (c) 2010 - 2012 ACIN, Profactor GmbH
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *   Michael Hofmann, Alois Zoitl, Ingo Hegny
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
#include "stringlist.h"

extern const CStringDictionary::TStringId g_nStringIdANY = 0;
extern const CStringDictionary::TStringId g_nStringIdANY_ADAPTER = 4;
extern const CStringDictionary::TStringId g_nStringIdANY_BIT = 16;
extern const CStringDictionary::TStringId g_nStringIdANY_ELEMENTARY = 24;
extern const CStringDictionary::TStringId g_nStringIdANY_INT = 39;
extern const CStringDictionary::TStringId g_nStringIdANY_MAGNITUDE = 47;
extern const CStringDictionary::TStringId g_nStringIdANY_NUM = 61;
extern const CStringDictionary::TStringId g_nStringIdANY_REAL = 69;
extern const CStringDictionary::TStringId g_nStringIdANY_STRING = 78;
extern const CStringDictionary::TStringId g_nStringIdARRAY = 89;
extern const CStringDictionary::TStringId g_nStringIdARTimeOut = 95;
extern const CStringDictionary::TStringId g_nStringIdATimeOut = 105;
extern const CStringDictionary::TStringId g_nStringIdBOOL = 114;
extern const CStringDictionary::TStringId g_nStringIdBYTE = 119;
extern const CStringDictionary::TStringId g_nStringIdCD = 124;
extern const CStringDictionary::TStringId g_nStringIdCDO = 127;
extern const CStringDictionary::TStringId g_nStringIdCLK = 131;
extern const CStringDictionary::TStringId g_nStringIdCNF = 135;
extern const CStringDictionary::TStringId g_nStringIdCO = 139;
extern const CStringDictionary::TStringId g_nStringIdCOLD = 142;
extern const CStringDictionary::TStringId g_nStringIdCTR = 147;
extern const CStringDictionary::TStringId g_nStringIdCU = 151;
extern const CStringDictionary::TStringId g_nStringIdCUO = 154;
extern const CStringDictionary::TStringId g_nStringIdCV = 158;
extern const CStringDictionary::TStringId g_nStringIdD = 161;
extern const CStringDictionary::TStringId g_nStringIdDATE = 163;
extern const CStringDictionary::TStringId g_nStringIdDATE_AND_TIME = 168;
extern const CStringDictionary::TStringId g_nStringIdDEV_MGR = 182;
extern const CStringDictionary::TStringId g_nStringIdDINT = 190;
extern const CStringDictionary::TStringId g_nStringIdDLY = 195;
extern const CStringDictionary::TStringId g_nStringIdDST = 199;
extern const CStringDictionary::TStringId g_nStringIdDT = 203;
extern const CStringDictionary::TStringId g_nStringIdDWORD = 206;
extern const CStringDictionary::TStringId g_nStringIdEI = 212;
extern const CStringDictionary::TStringId g_nStringIdEI0 = 215;
extern const CStringDictionary::TStringId g_nStringIdEI1 = 219;
extern const CStringDictionary::TStringId g_nStringIdEI2 = 223;
extern const CStringDictionary::TStringId g_nStringIdEMB_RES = 227;
extern const CStringDictionary::TStringId g_nStringIdEO = 235;
extern const CStringDictionary::TStringId g_nStringIdEO0 = 238;
extern const CStringDictionary::TStringId g_nStringIdEO1 = 242;
extern const CStringDictionary::TStringId g_nStringIdEO2 = 246;
extern const CStringDictionary::TStringId g_nStringIdEO3 = 250;
extern const CStringDictionary::TStringId g_nStringIdE_CTD = 254;
extern const CStringDictionary::TStringId g_nStringIdE_CTU = 260;
extern const CStringDictionary::TStringId g_nStringIdE_CTUD = 266;
extern const CStringDictionary::TStringId g_nStringIdE_CYCLE = 273;
extern const CStringDictionary::TStringId g_nStringIdE_DELAY = 281;
extern const CStringDictionary::TStringId g_nStringIdE_DEMUX = 289;
extern const CStringDictionary::TStringId g_nStringIdE_D_FF = 297;
extern const CStringDictionary::TStringId g_nStringIdE_F_TRIG = 304;
extern const CStringDictionary::TStringId g_nStringIdE_MERGE = 313;
extern const CStringDictionary::TStringId g_nStringIdE_PERMIT = 321;
extern const CStringDictionary::TStringId g_nStringIdE_RDELAY = 330;
extern const CStringDictionary::TStringId g_nStringIdE_REND = 339;
extern const CStringDictionary::TStringId g_nStringIdE_RESTART = 346;
extern const CStringDictionary::TStringId g_nStringIdE_RS = 356;
extern const CStringDictionary::TStringId g_nStringIdE_RTimeOut = 361;
extern const CStringDictionary::TStringId g_nStringIdE_R_TRIG = 372;
extern const CStringDictionary::TStringId g_nStringIdE_SELECT = 381;
extern const CStringDictionary::TStringId g_nStringIdE_SPLIT = 390;
extern const CStringDictionary::TStringId g_nStringIdE_SR = 398;
extern const CStringDictionary::TStringId g_nStringIdE_SWITCH = 403;
extern const CStringDictionary::TStringId g_nStringIdE_TRAIN = 412;
extern const CStringDictionary::TStringId g_nStringIdE_T_FF = 420;
extern const CStringDictionary::TStringId g_nStringIdE_TimeOut = 427;
extern const CStringDictionary::TStringId g_nStringIdG = 437;
extern const CStringDictionary::TStringId g_nStringIdGATE = 439;
extern const CStringDictionary::TStringId g_nStringIdGEN_CLIENT = 444;
extern const CStringDictionary::TStringId g_nStringIdGEN_E_DEMUX = 455;
extern const CStringDictionary::TStringId g_nStringIdGEN_E_MUX = 467;
extern const CStringDictionary::TStringId g_nStringIdGEN_PUBL = 477;
extern const CStringDictionary::TStringId g_nStringIdGEN_PUBLISH = 486;
extern const CStringDictionary::TStringId g_nStringIdGEN_SERVER = 498;
extern const CStringDictionary::TStringId g_nStringIdGEN_SUBL = 509;
extern const CStringDictionary::TStringId g_nStringIdGEN_SUBSCRIBE = 518;
extern const CStringDictionary::TStringId g_nStringIdID = 532;
extern const CStringDictionary::TStringId g_nStringIdIND = 535;
extern const CStringDictionary::TStringId g_nStringIdINIT = 539;
extern const CStringDictionary::TStringId g_nStringIdINITO = 544;
extern const CStringDictionary::TStringId g_nStringIdINT = 550;
extern const CStringDictionary::TStringId g_nStringIdK = 554;
extern const CStringDictionary::TStringId g_nStringIdLD = 556;
extern const CStringDictionary::TStringId g_nStringIdLDO = 559;
extern const CStringDictionary::TStringId g_nStringIdLINT = 563;
extern const CStringDictionary::TStringId g_nStringIdLREAL = 568;
extern const CStringDictionary::TStringId g_nStringIdLWORD = 574;
extern const CStringDictionary::TStringId g_nStringIdMGR = 580;
extern const CStringDictionary::TStringId g_nStringIdMGR_FF = 584;
extern const CStringDictionary::TStringId g_nStringIdMGR_ID = 591;
extern const CStringDictionary::TStringId g_nStringIdN = 598;
extern const CStringDictionary::TStringId g_nStringIdPERMIT = 600;
extern const CStringDictionary::TStringId g_nStringIdPV = 607;
extern const CStringDictionary::TStringId g_nStringIdQ = 610;
extern const CStringDictionary::TStringId g_nStringIdQD = 612;
extern const CStringDictionary::TStringId g_nStringIdQI = 615;
extern const CStringDictionary::TStringId g_nStringIdQO = 618;
extern const CStringDictionary::TStringId g_nStringIdQU = 621;
extern const CStringDictionary::TStringId g_nStringIdR = 624;
extern const CStringDictionary::TStringId g_nStringIdREAL = 626;
extern const CStringDictionary::TStringId g_nStringIdREQ = 631;
extern const CStringDictionary::TStringId g_nStringIdRESP = 635;
extern const CStringDictionary::TStringId g_nStringIdRMT_RES = 640;
extern const CStringDictionary::TStringId g_nStringIdRO = 648;
extern const CStringDictionary::TStringId g_nStringIdRQST = 651;
extern const CStringDictionary::TStringId g_nStringIdRSP = 656;
extern const CStringDictionary::TStringId g_nStringIdS = 660;
extern const CStringDictionary::TStringId g_nStringIdSINT = 662;
extern const CStringDictionary::TStringId g_nStringIdSTART = 667;
extern const CStringDictionary::TStringId g_nStringIdSTATUS = 673;
extern const CStringDictionary::TStringId g_nStringIdSTOP = 680;
extern const CStringDictionary::TStringId g_nStringIdSTRING = 685;
extern const CStringDictionary::TStringId g_nStringIdTIME = 692;
extern const CStringDictionary::TStringId g_nStringIdTIME_OF_DAY = 697;
extern const CStringDictionary::TStringId g_nStringIdTimeOut = 709;
extern const CStringDictionary::TStringId g_nStringIdTimeOutSocket = 717;
extern const CStringDictionary::TStringId g_nStringIdUDINT = 731;
extern const CStringDictionary::TStringId g_nStringIdUINT = 737;
extern const CStringDictionary::TStringId g_nStringIdULINT = 742;
extern const CStringDictionary::TStringId g_nStringIdUSINT = 748;
extern const CStringDictionary::TStringId g_nStringIdWARM = 754;
extern const CStringDictionary::TStringId g_nStringIdWORD = 759;
extern const CStringDictionary::TStringId g_nStringIdWSTRING = 764;
extern const CStringDictionary::TStringId g_nStringIdwARM = 772;
extern const CStringDictionary::TStringId g_nStringIdNextFreeId = 777;
extern const unsigned int cg_nNumOfConstStrings = 124;


#ifdef FORTE_STRING_DICT_FIXED_MEMORY
  CStringDictionary::TStringId CStringDictionary::scm_aunIdList[cg_unFORTE_StringDictInitialMaxNrOfStrings]
#else
  const CStringDictionary::TStringId CStringDictionary::scm_aunIdList[] 
#endif
  = {0, 4, 16, 24, 39, 47, 61, 69, 78, 89, 95, 105, 114, 119, 124, 127, 131, 135, 139, 142, 147, 151, 154, 158, 161, 163, 168, 182, 190, 195, 199, 203, 206, 212, 215, 219, 223, 227, 235, 238, 242, 246, 250, 254, 260, 266, 273, 281, 289, 297, 304, 313, 321, 330, 339, 346, 356, 361, 372, 381, 390, 398, 403, 412, 420, 427, 437, 439, 444, 455, 467, 477, 486, 498, 509, 518, 532, 535, 539, 544, 550, 554, 556, 559, 563, 568, 574, 580, 584, 591, 598, 600, 607, 610, 612, 615, 618, 621, 624, 626, 631, 635, 640, 648, 651, 656, 660, 662, 667, 673, 680, 685, 692, 697, 709, 717, 731, 737, 742, 748, 754, 759, 764, 772};

#ifdef FORTE_STRING_DICT_FIXED_MEMORY
  char CStringDictionary::scm_acConstStringBuf[cg_unFORTE_StringDictInitialStringBufSize]
#else
  const char CStringDictionary::scm_acConstStringBuf[] 
#endif
  = {"ANY\0ANY_ADAPTER\0ANY_BIT\0ANY_ELEMENTARY\0ANY_INT\0ANY_MAGNITUDE\0ANY_NUM\0ANY_REAL\0ANY_STRING\0ARRAY\0ARTimeOut\0ATimeOut\0BOOL\0BYTE\0CD\0CDO\0CLK\0CNF\0CO\0COLD\0CTR\0CU\0CUO\0CV\0D\0DATE\0DATE_AND_TIME\0DEV_MGR\0DINT\0DLY\0DST\0DT\0DWORD\0EI\0EI0\0EI1\0EI2\0EMB_RES\0EO\0EO0\0EO1\0EO2\0EO3\0E_CTD\0E_CTU\0E_CTUD\0E_CYCLE\0E_DELAY\0E_DEMUX\0E_D_FF\0E_F_TRIG\0E_MERGE\0E_PERMIT\0E_RDELAY\0E_REND\0E_RESTART\0E_RS\0E_RTimeOut\0E_R_TRIG\0E_SELECT\0E_SPLIT\0E_SR\0E_SWITCH\0E_TRAIN\0E_T_FF\0E_TimeOut\0G\0GATE\0GEN_CLIENT\0GEN_E_DEMUX\0GEN_E_MUX\0GEN_PUBL\0GEN_PUBLISH\0GEN_SERVER\0GEN_SUBL\0GEN_SUBSCRIBE\0ID\0IND\0INIT\0INITO\0INT\0K\0LD\0LDO\0LINT\0LREAL\0LWORD\0MGR\0MGR_FF\0MGR_ID\0N\0PERMIT\0PV\0Q\0QD\0QI\0QO\0QU\0R\0REAL\0REQ\0RESP\0RMT_RES\0RO\0RQST\0RSP\0S\0SINT\0START\0STATUS\0STOP\0STRING\0TIME\0TIME_OF_DAY\0TimeOut\0TimeOutSocket\0UDINT\0UINT\0ULINT\0USINT\0WARM\0WORD\0WSTRING\0wARM\0"};

 
